server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: analysis-app-login-auth-feign
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true