server:
  port: 8084
spring:
  profiles:
    active: dev
  application:
    name: analysis-app-login-auth
  main:
    allow-bean-definition-overriding: true
  freemarker:
    enabled: true
    # 是否启用模板缓存。
    cache: false
    # 模板编码
    charset: UTF-8
# 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
    allow-request-override: false
    # 是否检查模板位置是否存在。
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
# 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性
    allow-session-override: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    expose-spring-macro-helpers: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
ribbon:
  eureka:
    enabled:true

# 配置freemark
