server:
  port: 8088
spring:
  profiles:
    active: dev
  application:
    name: analysis-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangzuozhanglina/analysis-document.git
          username: zhangzuozhanglina
          password: 19950519zzz
          search-paths: config-center/yml
