server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: analysis-app-login-auth
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 20
        min-idle: 5
  freemarker:
    enabled: true
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    allow-session-override: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
ribbon:
  eureka:
    enabled:true


# 配置freemark
